-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 147.592 s <<< FAILURE! - in TestSuite
TestCaseController(runner.TestController)  Time elapsed: 124.556 s  <<< FAILURE!
java.lang.reflect.InvocationTargetException
	at runner.TestController.TestCaseController(TestController.java:79)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at runner.TestController.TestCaseController(TestController.java:79)

